name: mistake_book
description: Offline Error Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  path: any
  receive_sharing_intent: any
  image_picker: any

flutter:
  uses-material-design: true
